Ignore nmbd start errors when there is no non-loopback interface (Closes: #893762)

diff --git a/debian/samba.postinst b/debian/samba.postinst
--- a/debian/samba.postinst
+++ b/debian/samba.postinst
@@ -2,6 +2,17 @@
 
 set -e
 
+nmbd_error_handler() {
+    if [ -d /sys/class/net/lo ] && ls /sys/class/net/lo | grep -qv ^lo$; then
+        # https://bugs.debian.org/893762
+        echo 'WARNING: nmbd failed to start as there is no non-loopback interface.'
+        echo 'Either add an interface or set "disable netbios = yes" in smb.conf and run "systemctl mask nmbd"'
+        return 0
+    else
+        return 1 # caught by set -e
+    fi
+}
+
 mask_services() {
     local reason="$1"
     shift
